application: book-wall
version: 1
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: PIL
  version: latest

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /docs
  static_dir: docs

- url: /assets
  static_dir: assets

- url: .*
  script: main.app


